// <auto-generated />
namespace WebApplication9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class taikhoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(taikhoan));
        
        string IMigrationMetadata.Id
        {
            get { return "202303150912593_'tai khoan'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
